### PR TITLE
Fixes bugs in upwinding on surface flow

### PR DESCRIPTION
**Pull request by ecoon**
fixes bugs in upwinding with zero gradient condition, and fixes display error in overland conductivity for Neumann boundary faces.  Some of these changes may need to be moved into Richards and energy equations as well, at least the upwinding on Neumann face issues, but this will take some thought to make sure they don't break surface-subsurface coupling via boundary_face.

Addresses #11 

This probably isn't complete yet -- it needs to deal with the same issue in the subsurface, and potentially with advection of energy as well?

### CODE REVIEW

**Comment by ecoon** [comment]
@ajkhattak can you remind me of the issue you had with surface flow and advection of energy associated with boundary faces?  I'll look at your pull request now, and see how these two pull requests overlap/interact.

**Comment by ecoon** [comment]
@dasvyat Note, Daniil, this is the same commit that I asked you to look at yesterday, but I put it on a different branch to make it a bit cleaner to review.

**Comment by dasvyat** [comment]
Do you think it is worthwhile to compute actual tolerance as fraction of maximum absolute value of the flux, where the values of the fraction is a parameter.

**Comment by ecoon** [comment]
Ahmad is going to do some testing of this pull request as a part of testing the other pull request, 

https://github.com/amanzi/ats/pull/9

**Pull request merged**
