### PR TITLE
Update ats-ci.yml to build images for arm64

### PR DESCRIPTION
**Pull request by rfiorella**
Updates the ats-ci.yml GitHub action to build images for both amd64 and arm64 using buildx. It is built on the TPLs image, which is currently only amd64 and will need to be updated as well.

Currently only runs the tests on the amd64 image. I think the CI action could be modified to run on both architectures - let me know if this would be preferred and I'll update the PR. 

One of the regression tests fails on a local test of the arm64 image, but this was due to the timeout threshold being too low. I suspect that this issue will go away when the TPL image is also built for arm64.

### CODE REVIEW

**Comment by ecoon** [comment]
That sounds great.  I don't have an opinion either way on whether tests should run on both.  If they're slow, let's just run amd64.

**Comment by jd-moulton** [comment]
The tests don't take that long to run (usually), particularly compared to the build itself.  So I think the goal should be to run the tests on both architectures.

**Comment by ecoon** [comment]
Yeah, that's a fair point.  What is the plan for TPLs then?  Is that getting updated in Amanzi, and this PR should wait until that one is done?  Or should we accept this one, make a ticket, and then do a second PR once @rfiorella is ready to turn on arm tests?

**Comment by rfiorella** [comment]
Converted PR to draft as compiling TPLs and ATS is unworkably slow. Looking into a few alternatives (primarily Azure pipelines and/or [cross-compiling](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/)).

**Comment by ecoon** [comment]
@rfiorella  Where are we at with this?  I've noticed that our current images are not debuggable -- if you install gdb into the container after a CI has failed, I get a bunch of errors about ptrace that suggest that the problem might be fixed by building an arm64 container, see docker/for-mac#5191 , so I'm interested in checking that if this is ready to go.

**Comment by rfiorella** [comment]
@ecoon I do remember having some CI failures on arm64/aarch64 images but not the the x86 ones, maybe this is the same issue. We can build arm64/aarch64 images for amanzi and ats fine, I think I've manually added a few versions here and there (e.g., for the IDEAS all hands), but it didn't work on CI as compiling through the QEMU emulator was fatally slow (like 10x longer).

Assuming GitHub doesn't roll out arm64 runners and make this a lot easier, @jd-moulton and I had a few discussions about either using cross-compilers (which we could include in the tpls image, but would have to update all the cmake workflows to pick up these compilers in a cross compiling case) or using a self-hosted arm64 runner somewhere. The latter has some issues that maybe we should talk about in a different venue, but might be a possibility of cross-compiling doesn't work   

I had tried the cross-compiler route a few months ago but was pulled away by other priorities before I could fix the cmake part of it and it seemed like lower priority when we could just have occasional releases - obviously though if we want to include this in CI we'll have to revisit.

**Comment by rfiorella** [comment]
This is stale and GitHub still provides no runners that have both arm64 and allow use of docker (most recent macOS runners are arm64, but there seem to be issues with existing GitHub actions on arm, e.g.: https://github.com/marketplace/actions/setup-docker-on-macos)

Closing for now since a new approach is needed, such as:
a) could try `brew install --cask docker`  on macOS arm64 runner free tier
b) compile through emulation (but, extremely slow)
c) cross-compile (but, somewhat messy and inflates image size)
d) deploy to linux arm runners (but, costs $)
e) run arm64 tasks on a self-hosted runner somewhere

**Pull request closed without merging**
