### PR TITLE
Dsv/merge master chemistry

### PR DESCRIPTION
**Pull request by ajkhattak**

### CODE REVIEW

**Comment by ecoon** [comment]
Is this ready to go yet?  Holler when it is.

**Comment by ecoon** [comment]
@ajkhattak  @dasvyat  Are you guys happy with this yet?  Is the Amanzi pull request done?  Just would like to clean this up soon.

**Comment by ajkhattak** [comment]
There is a little change to the order of initialization in the coordinator.cc (line 224), so I am not sure if it will break anything. I added this because in the reactive transport runs the primary variables were not getting properly initialized after merging recent master within dsv/merge_master_chemistry. They are initialized through State "initial conditions".

**Comment by ecoon** [comment]
@ajkhattak did you run the regression tests?  All currently pass on master.

**Comment by ajkhattak** [comment]
sorry, not yet, will work on it probably today, if not then tomorrow.

**Pull request merged**
