### PR TITLE
Maximum saturated concentration of components

### PR DESCRIPTION
**Pull request by hiter-joe**
Hey team,
I have made some changes to transport_ats_pk.cc and transport_ats.hh files in version ATS_1.4.1_797362e.

The main change is adding a limitation of transport solute or species. (Line 66 in transport_ats_pk.cc and Line 552 in transport_ats.hh)
If the concentration is larger than component max concentration. 1. it will assign the max value to tcc. 2. The oversaturated part will be saved to solid. (Line 1367 in transport_ats_pk.cc

I have tested using a 2D transect and it works for my case. 
Please remember to add the "component max saturations" value in XML transport section. 

I add a zip file here and also you can find the update version in my Github.  
https://github.com/hiter-joe/ats/blob/master/src/pks/transport/transport_ats.hh
https://github.com/hiter-joe/ats/blob/master/src/pks/transport/transport_ats_pk.cc
[Modification.zip](https://github.com/amanzi/ats/files/12185912/Modification.zip)

Please let me know if there any questions or requirements.
Thanks,
Bing

### CODE REVIEW

**Comment by smolins** [comment]
- Is the reason concentrations increase when ET or freezing take place because the mass balance for ET and freezing is done with just water, i.e. H2O, not with the solution? For example, is frozen water simply water and no concentrations are assigned to it?

- The geochemical evolution of a solution when H2O evaporates, e.g. what phases precipitate out, is a lot more complex than simply taking out the mass of the solutes and assigning them to a solid residue. So even if the approach PR will be able to handle the issue at hand, I would be very careful in taking results from this as valid for geochemical models. Maybe a case study (say example or test simulation) would help in framing what type of problem this approach would target rather than giving the impression this is a valid approach for other problems. 

- Is the maximum total concentration a required parameter in this PR? If so, I would disagree with this for the reason above.  It is more likely to confuse users than help them.

**Comment by hiter-joe** [comment]
Hi Sergi,
Regarding the "maximum total concentration" parameter in the PR method,  it is currently required. I can update the code and make it a non-required parameter with a default value. it will provide more flexibility to users and avoid potential confusion.

I completely agree with your point about the complexity of geochemical evolution during ET processes. While the current threshold approach on concentration is a quick and simple solution for our immediate purpose, it may not fully capture the intricacies involved. If we wish to develop a more sophisticated method, it would be beneficial to engage in further discussions and exploration.

I think the issue with large concentrations after ET processes could be influenced by two processes.

Firstly, the increase in concentration after ET. The value of concentration depends on the strength of ET and simulation setup. Applying some limitations on concentration might be reasonable, whether using the simple PR method or a more complex geochemical model.

Secondly, the role of water saturation should also be considered. The mass of solute is currently calculated in the transport_ats_pk.cc file using the old concentration and current water saturation. Should we rebalance the old concentration considering the ET process and strong precipitation, as this might impact the current water saturation and concentration of solute in mixed water and rainfall.

I did not go further along the second point because Ethan mentioned ATS may want to rewrite the transport_ats_pk part based on Phong's finding. If I am wrong, please correct me here.

Please let me know if you have more comments, and I'm eager to learn from you all.

Best,
Bing

**Comment by ecoon** [comment]
@smolins @hiter-joe 

Sorry for being so late to this party.  

@smolins. Yes, freezing or evaporation are assumed to be "water only." My understanding is that this is reasonable for most aqueous components?  At least salinity is the key one that is frequently needed.

Currently, if freezing or evaporation are enough to remove all water, the number of mols of C left are dumped into the solid residue.  As evaporation and freezing take away water but not C, concentrations grow and can break chemistry because they get too big.

My understanding is that:
1. growing concentration is correct
2. we need to solve chemistry for these large concentrations even if it is for a very short dt -- we're just trying to get through the step
3. While simply "solidifying out" C is probably not geochemically correct, it is "good enough" to hold onto the mols of C and conserve mass for simple cases.

So I agree that we should not have a "user-required max concentration" but that we can have this as an optional parameter as a way to "get through a tough timestep" while both conserving mass and not crashing PFLOTRAN.  I believe that Bing is definitely not expecting PFLOTRAN to give accurate reaction rates at these high Cs, but is just hoping to keep making it through the run that is otherwise not often affected.

@hiter-joe  I think you set the targets for this PR incorrectly though.  I'll go digging into the patch you sent and the files you link in your own repo, but you probably want this to be a PR from your fork's master to our master, not from our master to 1.4 as it currently is.

**Comment by hiter-joe** [comment]
Hi Ethan,

I've recently made an update to the patch. In my case, an extremely high value of C is uncommon. However, it does disrupt the reaction process in PFLOTRAN. As a remedy, I've set a cap to transition it to the solid phase. It's a straightforward solution, but it's effective for my current needs. I'll integrate this change into the forked version soon. 

Additionally, I'm implementing Jianqiu's salinity function for the reaction process in ATS-PFLOTRAN. I've faced challenges in matching versions between Alquimia and ATS-PFLOTRAN, but with Glenn's assistance, we've resolved the issue. I'm hopeful we can incorporate this new feature soon after some tests. 

Btw, is there any updates or progress on ATS-ELM coupling? Because I plan to couple ELM's carbon pool to ATS and PFLOTRAN. Although some weak coupling can be done, i am still wondering your progress on this. 

Thanks
Bing

**Comment by ecoon** [comment]
This PR is replaced by #213

**Comment by ecoon** [comment]
@hiter-joe See the new PR, which I think should do what you were doing in this PR (basically just a rename of some variables).  

What did you have to do on salinity to ATS?  Was it changes to ATS or to Alquimia or to PFLOTRAN?

ATS-ELM coupling is working now, but still needs some cleanup work.  We've demonstrated a few simple problems at the COMPASS-GLM All Hands in serial.

**Pull request closed without merging**
